# Generated by Django 5.1.7 on 2025-05-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titel',
            field=models.CharField(default='Titel', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
