# Generated by Django 5.1.7 on 2025-06-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='main_Tag',
            field=models.CharField(choices=[('1', '1AHIT'), ('2', '2AHIT'), ('3', '3AHIT'), ('4', '4AHIT'), ('5', '5AHIT')], max_length=20),
        ),
    ]
