# Generated by Django 5.1.7 on 2025-05-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_titel_alter_post_image_file'),
        ('login', '0002_remove_user_class_remove_user_deparment_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
