# Generated by Django 5.1.7 on 2025-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_post_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titel',
            field=models.CharField(default='Titel', max_length=255),
        ),
    ]
