# Generated by Django 5.1.7 on 2025-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('Class', models.CharField(choices=[('1a', '1A'), ('1b', '1B'), ('2a', '2A'), ('2b', '2B'), ('3a', '3A'), ('3b', '3B'), ('4a', '4A'), ('4b', '4B'), ('5a', '5A'), ('5b', '5B')], max_length=3)),
                ('deparment', models.CharField(choices=[('IT', 'HIT'), ('WIM', 'HWIM'), ('MBA', 'HMBA'), ('ET', 'HET'), ('AFME', 'AFME')], max_length=5)),
            ],
        ),
    ]
