# Generated by Django 5.1.7 on 2025-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deparment',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[(0, 'admin'), (1, 'schueler')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
